### ISSUE TITLE
get_third_party.sh下载失败

### ISSUE THREAD

**Issue by Billchen28** [Tencent/MSEC#32]
download zlib for monitor_server:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
--2017-01-24 13:54:48--  http://zlib.net/zlib-1.2.8.tar.gz
正在解析主机 zlib.net (zlib.net)... 69.73.132.10
正在连接 zlib.net (zlib.net)|69.73.132.10|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2017-01-24 13:54:49 错误 404：Not Found。

**Comment by msecowner** [comment]
收到，我们看一下，应该是zlib发新版本了，1.2.8挪到其他目录了

**Comment by msecowner** [comment]
ok，fixed。thank you
