### ISSUE TITLE
有可能的内存泄漏

### ISSUE THREAD

**Issue by mjammer** [Tencent/MSEC#33]
`bool CShmMgr::GetAllServiceKeys()`中return false之后data没有删除

**Comment by msecowner** [comment]
thanks, fix the bug just now.

**Comment by mjammer** [comment]
MSEC/monitor/server/src/shm_mgr.cpp 中也是，有两处。

**Comment by mjammer** [comment]
MSEC/monitor/server/src/shm_mgr.cpp 中也是，有两处。 @msecowner
