### ISSUE TITLE
没有提供监控服务单品的镜像下载地址

### ISSUE THREAD

**Issue by Michael-LiK** [Tencent/MSEC#49]
monitor_standalone.tar.gz和monitor_standalone_agent.tar.gz
没有下载链接。

**Comment by daiziyi** [comment]
`version 2.0(2016.12.31)`
下载连接中的tar包，解压下包含上述包的。
 https://share.weiyun.com/fcc59ff8a101819817f2aa26e2a77826 


**参考来源**：
./download/
https://github.com/Tencent/MSEC/tree/master/download

**Comment by Michael-LiK** [comment]
非常感谢




| |
李裕昊michael
邮箱：qd_liyuhao@yeah.net
|

签名由 网易邮箱大师 定制

在2018年09月28日 16:02，daiziyi 写道：

version 2.0(2016.12.31)
下载连接中的tar包，解压下包含上述包的。
https://share.weiyun.com/fcc59ff8a101819817f2aa26e2a77826

参考来源：
./download/
https://github.com/Tencent/MSEC/tree/master/download
